CREATE TABLE "page_forms" (
	"external" text,
	"fields" jsonb NOT NULL,
	"intro" text NOT NULL,
	"note" text,
	"slug" text PRIMARY KEY NOT NULL,
	"submit" text NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
INSERT INTO "page_forms" ("slug", "external", "fields", "intro", "note", "submit") VALUES
($$agent-allotment$$, NULL, $$[{"label":"Agent code","name":"code"},{"label":"Password","name":"password","type":"password"}]$$::jsonb, $$View seat and route allotment for a registered agent.$$, NULL, $$View allotment$$),
($$cancel-ticket$$, NULL, $$[{"label":"Ticket number","name":"ticket","placeholder":"e.g. 24051234567"},{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"}]$$::jsonb, $$Cancel a confirmed GSRTC ticket. Cancellation charges apply based on how far from departure you cancel; the balance is refunded to the original payment method.$$, $$Refunds are processed within 7–10 working days.$$, $$Find ticket to cancel$$),
($$e-top-status$$, NULL, $$[{"label":"Transaction ID","name":"txn","placeholder":"e.g. ETOP123456"}]$$::jsonb, $$Check the status of an agent e-top-up (wallet recharge) request.$$, NULL, $$Check e-top status$$),
($$gsrtc-agent-login$$, $$https://www.gsrtc.in/OPRSWeb/preUserAuthenticate.do$$, $$[{"label":"Agent ID / username","name":"user"},{"label":"Password","name":"password","type":"password"}]$$::jsonb, $$Portal login for GSRTC booking agents.$$, NULL, $$Open agent portal$$),
($$new-agent-register$$, NULL, $$[{"label":"Full name","name":"name"},{"label":"Mobile","name":"mobile","type":"tel"},{"label":"Email","name":"email","type":"email"},{"label":"Preferred division","name":"division","options":["Ahmedabad","Vadodara","Surat","Rajkot","Bhavnagar","Mehsana","Other"],"type":"select"},{"label":"PAN","name":"pan"}]$$::jsonb, $$Apply to become an authorised GSRTC booking agent. We review applications and respond by email.$$, $$Registration is subject to GSRTC's franchisee terms & conditions.$$, $$Submit application$$),
($$new-commuter-bus-pass$$, NULL, $$[{"label":"Full name","name":"name"},{"label":"Mobile","name":"mobile","type":"tel"},{"label":"From (boarding point)","name":"from"},{"label":"To (destination)","name":"to"},{"label":"Pass type","name":"type","options":["Daily","Monthly","Quarterly","Student"],"type":"select"}]$$::jsonb, $$Apply for a new monthly commuter bus pass online. Bring the reference number and a photo ID to any bus station to collect the pass.$$, NULL, $$Apply for pass$$),
($$print-sms-ticket$$, NULL, $$[{"label":"Ticket number","name":"ticket","placeholder":"e.g. 24051234567"},{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"}]$$::jsonb, $$Reprint your e-ticket or resend it to your phone by SMS.$$, NULL, $$Retrieve ticket$$),
($$refund-complaint$$, NULL, $$[{"label":"Ticket number","name":"ticket","placeholder":"e.g. 24051234567"},{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"},{"label":"Email","name":"email","placeholder":"you@example.com","type":"email"},{"full":true,"label":"Describe the issue","name":"details","type":"textarea"}]$$::jsonb, $$Raise a complaint for a refund that has not been credited. Our team responds within 3 working days.$$, NULL, $$Submit complaint$$),
($$refund-transaction-enquiry$$, NULL, $$[{"label":"Transaction / ticket number","name":"txn","placeholder":"e.g. TXN123456"},{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"}]$$::jsonb, $$Track the status of a refund or a payment that did not complete against your booking.$$, NULL, $$Check refund status$$),
($$reschedule-my-journey$$, NULL, $$[{"label":"Ticket number","name":"ticket","placeholder":"e.g. 24051234567"},{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"},{"label":"New date of journey","name":"date","type":"date"}]$$::jsonb, $$Move an existing booking to a different date or service. Rescheduling is allowed once, up to a set time before departure.$$, $$A fare difference may apply for the new service.$$, $$Find booking$$),
($$sharvan-tirth-darshan$$, $$https://yatradham.gujarat.gov.in/Booking$$, $$[{"label":"From","name":"from"},{"label":"Travel date","name":"date","type":"date"}]$$::jsonb, $$Special pilgrimage bus services connecting Gujarat's revered temples under the Sharvan Tirth Darshan scheme.$$, NULL, $$Check yatra services$$),
($$unity-booking$$, $$https://www.soutickets.in/#/gsrtc-booking$$, $$[{"label":"From","name":"from"},{"label":"Date of visit","name":"date","type":"date"},{"label":"Visitors","name":"visitors","options":["1","2","3","4","5","6"],"type":"select"}]$$::jsonb, $$Book GSRTC buses to the Statue of Unity at Kevadia and its attractions.$$, NULL, $$Continue to Unity booking$$),
($$view-history$$, NULL, $$[{"label":"Registered mobile","name":"mobile","placeholder":"10-digit number","type":"tel"},{"label":"Password / OTP","name":"password","type":"password"}]$$::jsonb, $$View your past bookings, cancellations and transactions.$$, NULL, $$View history$$),
($$waiting-list-ticket-status$$, NULL, $$[{"label":"Ticket / PNR number","name":"ticket","placeholder":"e.g. 24051234567"}]$$::jsonb, $$Check whether a waiting-list ticket has moved to confirmed.$$, NULL, $$Check status$$);
