/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TrackRouteImport } from './routes/track'
import { Route as BookTripIdRouteImport } from './routes/book.$tripId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PaymentReturnRouteImport } from './routes/payment.return'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentsDodoWebhookRouteImport } from './routes/api/payments/dodo/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTripIdRoute = BookTripIdRouteImport.update({
  id: '/book/$tripId',
  path: '/book/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentReturnRoute = PaymentReturnRouteImport.update({
  id: '/payment/return',
  path: '/payment/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsDodoWebhookRoute = ApiPaymentsDodoWebhookRouteImport.update({
  id: '/api/payments/dodo/webhook',
  path: '/api/payments/dodo/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/dodo/webhook': typeof ApiPaymentsDodoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/dodo/webhook': typeof ApiPaymentsDodoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/book/$tripId': typeof BookTripIdRoute
  '/p/$slug': typeof PSlugRoute
  '/payment/return': typeof PaymentReturnRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payments/dodo/webhook': typeof ApiPaymentsDodoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/search'
    | '/track'
    | '/book/$tripId'
    | '/p/$slug'
    | '/payment/return'
    | '/api/auth/$'
    | '/api/payments/dodo/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/search'
    | '/track'
    | '/book/$tripId'
    | '/p/$slug'
    | '/payment/return'
    | '/api/auth/$'
    | '/api/payments/dodo/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/search'
    | '/track'
    | '/book/$tripId'
    | '/p/$slug'
    | '/payment/return'
    | '/api/auth/$'
    | '/api/payments/dodo/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  TrackRoute: typeof TrackRoute
  BookTripIdRoute: typeof BookTripIdRoute
  PSlugRoute: typeof PSlugRoute
  PaymentReturnRoute: typeof PaymentReturnRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentsDodoWebhookRoute: typeof ApiPaymentsDodoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tripId': {
      id: '/book/$tripId'
      path: '/book/$tripId'
      fullPath: '/book/$tripId'
      preLoaderRoute: typeof BookTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/return': {
      id: '/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof PaymentReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/dodo/webhook': {
      id: '/api/payments/dodo/webhook'
      path: '/api/payments/dodo/webhook'
      fullPath: '/api/payments/dodo/webhook'
      preLoaderRoute: typeof ApiPaymentsDodoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  TrackRoute: TrackRoute,
  BookTripIdRoute: BookTripIdRoute,
  PSlugRoute: PSlugRoute,
  PaymentReturnRoute: PaymentReturnRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentsDodoWebhookRoute: ApiPaymentsDodoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
