// AUTO-GENERATED by scripts/gen-page-content.mjs — scraped from gsrtc.in.
// Edit the scraper output and re-run, not this file by hand.
import { CANCELLATION_POLICY_BULLETS } from "#/data/cancellation-policy";

export interface PageSection {
	bullets?: string[];
	heading?: string;
	paragraphs?: string[];
}

export interface PageContact {
	address?: string;
	email?: string;
	phone?: string;
}

export interface PageContent {
	contact?: PageContact;
	intro?: string;
	sections?: PageSection[];
}

export const PAGE_CONTENT: Record<string, PageContent> = {
	"about-us": {
		intro:
			"Gujarat State Road Transport Corporation (GSRTC) is a passenger transport body established on May 1, 1960, providing bus services across Gujarat and neighbouring states with extensive infrastructure and technology.",
		sections: [
			{
				heading: "Organization Overview",
				paragraphs: [
					"Established on May 1, 1960 alongside Gujarat's formation, GSRTC has grown from 7 divisions to 16 divisions, operating 8,322 buses across 127 depots and 226 bus stations.",
				],
			},
			{
				bullets: [
					"More than 39,795 employees",
					"226 bus stations and 1,554 pick-up stands",
					"127 depot workshops, 16 divisional workshops, and one central workshop",
					"7 tyre retreading plants and a bus body building facility producing 1,000 bodies annually",
				],
				heading: "Key Statistics",
			},
			{
				bullets: [
					"14,000 electronic ticketing machines",
					"Online reservation and e-ticketing systems",
					"Computerized daily and student pass issuance",
					"Integrated depot management systems across all locations",
					"Video conferencing between central and divisional offices",
				],
				heading: "Technology & E-Governance",
				paragraphs: [
					"GSRTC pioneered GPS and passenger information systems for bus tracking.",
				],
			},
		],
	},
	achievements: {
		intro:
			"This page highlights GSRTC's operational scale, fleet modernization, service improvements, and technological innovations in public transport.",
		sections: [
			{
				heading: "GSRTC at a Glance",
				paragraphs: [
					"GSRTC operates 125 depots, 16 divisions, and a Central Office / Central Workshop, running about 8,229 buses serving 27 lakh daily passengers across 99.34% of Gujarat's villages.",
				],
			},
			{
				heading: "Fleet Rejuvenation",
				paragraphs: [
					"GSRTC inducted 12,812 new buses over ten years with Rs 3,839.63 Cr in government support, introducing sleeper, AC, and luxury coaches. Over-aged buses fell from 74.75% (2006-07) to 22.80% (2024-25).",
				],
			},
			{
				bullets: [
					"Load Factor increased to 75.07%",
					"Vehicle Utilization rose to 469 km daily",
					"Breakdown Rate down to 0.00 per 10,000 km",
					"Accident Rate maintained at 0.06 per 1 lakh km",
				],
				heading: "Efficiency Improvements (since 2021-22)",
			},
			{
				bullets: [
					"Discounted monthly passes at 40% of regular fare",
					"Free travel for girl and ITI students",
					"Increased free luggage allowance of 25 kg",
					"Digital integration across 17 schemes",
				],
				heading: "Passenger-Friendly Measures",
			},
			{
				bullets: [
					"GPS/PIS bus tracking",
					"14,000 electronic ticketing machines",
					"Online reservations and integrated depot and inventory management",
					"3,000 smart payment-enabled ticketing machines",
				],
				heading: "E-Governance Initiatives",
			},
		],
	},
	"annual-audit-report": {
		intro:
			"This page provides access to GSRTC's annual audit reports, allowing stakeholders to review financial and operational audits across multiple fiscal years. Each report is available as a downloadable PDF.",
		sections: [
			{
				bullets: [
					"GSRTC Annual Audit Report 2021-22",
					"GSRTC Annual Audit Report 2020-21",
					"GSRTC Annual Audit Report 2019-20",
				],
				heading: "Available Reports",
			},
		],
	},
	awards: {
		intro:
			"This page documents the many national awards GSRTC has received across decades, recognizing excellence in fuel efficiency, vehicle productivity, cost management, safety, and technological innovation.",
		sections: [
			{
				heading: "Overview",
				paragraphs: [
					"GSRTC has received a number of national awards for its performance in various fields such as productivity and fuel conservation. The awards table lists 63 items spanning 1978-79 through 2021-22.",
				],
			},
			{
				bullets: [
					"Multiple wins for Highest Improvement/Achievement in Diesel KMPL across consecutive years (1978-79 through 1993-94)",
					"Consistent Improvement Diesel KMPL special award in 1996-97",
				],
				heading: "Early Recognition (1978-1997)",
			},
			{
				bullets: [
					"Highest KMPL in Fuel Efficiency (5.42) for 2013-14 among STUs operating Mofussil Services, for a fourth consecutive year",
					"Platinum SKOCH Award 2019 for in-house body building and Command and Control Center",
					"Kaushalacharya award for recruiting the highest number of apprentices over four years",
					"World Record India for Maximum Online Passenger Travel Campaign (2021-22)",
				],
				heading: "Recent Achievements (2013-2022)",
			},
		],
	},
	"blacklisted-agencies": {
		intro:
			"A list of agencies, vendors, and individuals blacklisted by GSRTC for violations such as non-payment of license fees, failure to supply materials, unauthorized business practices, and contractual breaches. The table documents 162 blacklisted entities across divisions, spanning 2020 to 2026.",
		sections: [
			{
				bullets: [
					"Irregular or failure to pay license fees",
					"Incomplete documentation submissions",
					"Retreat from or discontinuation of assigned business",
					"Sale of unauthorized goods",
					"Poor behavior or misconduct",
					"Failure to supply materials per specifications",
					"Non-compliance with tender conditions",
				],
				heading: "Common Blacklist Reasons",
			},
			{
				bullets: [
					"Stall licensees and vendors (cutlery, dry fruits, stationery, mobile stands)",
					"Canteen and food service operators",
					"Parking attendants",
					"Suppliers and contractors",
					"Service providers",
				],
				heading: "Affected Business Types",
			},
			{
				heading: "Geographic Coverage",
				paragraphs: [
					"Blacklisted agencies span divisions including Valsad, Palanpur, Nadiad, Himmatnagar, Godhra, Junagadh, Bharuch, and Rajkot.",
				],
			},
			{
				heading: "Entry Details",
				paragraphs: [
					"Each entry includes serial number, division/department, location, business type, party name, deposit amount, violation reason, start date, end date, and administrative order reference.",
				],
			},
		],
	},
	"booking-policies": {
		intro:
			"Policies and procedures governing online and mobile bus ticket bookings through GSRTC, covering reservations, cancellations, refunds, and passenger responsibilities.",
		sections: [
			{
				heading: "Booking Requirements & Charges",
				paragraphs: [
					"To advance-book, the distance between boarding point and destination must be at least 50% of the route for premium buses and 20% for other types. Online/mobile booking carries a Rs. 5 charge; current booking has no charge. Advance booking is available up to 60 days, and trip sheets are prepared 30 minutes before departure.",
				],
			},
			{
				bullets: [
					"Children under 5 years qualify as children (free)",
					"Children aged 5-12 receive half-price tickets",
				],
				heading: "Child Age Criteria",
			},
			{
				bullets: [...CANCELLATION_POLICY_BULLETS],
				heading: "Cancellation Charges",
			},
			{
				heading: "Refund & Rescheduling",
				paragraphs: [
					"Refund requests within 30 days; full/partial refunds if the bus is delayed more than 2 hours or the service is partially operated or not operated. Rescheduling is valid up to 24 hours before departure, only one reschedule permitted, to same or higher class only.",
				],
			},
			{
				heading: "E-Ticket & Support",
				paragraphs: [
					"Maximum 6 seats per ticket; tickets sent via SMS/WhatsApp; passengers must arrive 15 minutes early. Daily booking closure is 23:50 to 00:20; failed-transaction refunds process in 7-10 days. Toll-free: 1800 233 666666; Email: customer-support@gsrtc.org.",
				],
			},
		],
	},
	"bus-enquiry": {
		intro:
			"Bus and booking enquiry phone numbers across all Gujarat State Road Transport Corporation divisions and bus stations throughout Gujarat.",
		sections: [
			{
				bullets: [
					"Ahmedabad (17 locations)",
					"Amreli (14)",
					"Baroda (14)",
					"Bhavnagar (13)",
					"Bharuch (14)",
					"Bhuj (12)",
					"Godhra (18)",
					"Himmatnagar (17)",
					"Jamnagar (10)",
					"Junagadh (24)",
					"Mahesana (15)",
					"Nadiad (26)",
					"Palanpur (15)",
					"Rajkot (20)",
					"Surat (22)",
					"Valsad (16)",
				],
				heading: "Bus & Booking Enquiry Numbers",
				paragraphs: [
					"Enquiry numbers are organized by 16 regional divisions, each with a table of bus stand or control point locations and their phone numbers. Example: Ahmedabad Central Bus Station (079-25463409).",
				],
			},
		],
	},
	"contact-us": {
		contact: {
			address:
				"Central Office, Near Ranip Bus Terminal, Ranip, Ahmedabad - 382480",
			email:
				"refund@gsrtc.org (refunds); customer-support@gsrtc.org (customer support)",
			phone: "Toll Free: 1800 233 666666",
		},
		intro:
			"Contact information and resources for the Gujarat State Road Transport Corporation (GSRTC), Gujarat's state-run bus transportation service.",
		sections: [
			{
				bullets: [
					"Central Office, Near Ranip Bus Terminal, Ranip, Ahmedabad - 382480",
					"Toll Free: 1800 233 666666",
					"Refund email: refund@gsrtc.org",
					"Customer Support: customer-support@gsrtc.org",
				],
				heading: "Corporate Headquarters",
			},
			{
				bullets: [
					"Divisions directory",
					"Corporate office details",
					"Bus inquiry system",
				],
				heading: "Quick Links",
			},
			{
				heading: "Additional Resources",
				paragraphs: [
					"Navigation to sections on recruitment, grievance redressal for persons with disabilities, service regulations, and citizen rights documentation, plus links to the GSRTC mobile apps for Android and iOS.",
				],
			},
		],
	},
	"corporate-office": {
		contact: {
			email: "customer-support@gsrtc.org",
			phone: "Toll-free helpline: 1800 233 666666",
		},
		intro:
			"Contact details for the Gujarat State Road Transport Corporation's corporate office leadership and departmental heads, so stakeholders can reach the right officials.",
		sections: [
			{
				bullets: [
					"Vice Chairman & Managing Director (Fax: 22803065)",
					"Executive Director (Vigilance) (Fax: 22822216)",
					"General Manager (Administration) - 079-22820985",
					"General Manager (Operation) - 079-22812416",
				],
				heading: "Corporate Office Directory",
				paragraphs: [
					"The directory lists 23 positions within GSRTC's organizational hierarchy, covering operations, civil and mechanical engineering, traffic and commerce, technology, personnel, procurement, legal affairs, and security.",
				],
			},
		],
	},
	divisions: {
		intro:
			"A contact directory for the Gujarat State Road Transport Corporation, listing divisional officials and depot managers across 16 regional divisions with their mobile numbers.",
		sections: [
			{
				bullets: [
					"Ahmedabad",
					"Amreli",
					"Baroda",
					"Bharuch",
					"Bhavnagar",
					"Bhuj",
					"Godhra",
					"Himmatnagar",
					"Jamnagar",
					"Junagadh",
					"Mehsana",
					"Nadiad",
					"Palanpur",
					"Rajkot",
					"Surat",
					"Valsad",
				],
				heading: "GSRTC Divisions",
				paragraphs: [
					"GSRTC operations are organized across 16 regional divisions, each with its own set of officials and depot managers.",
				],
			},
			{
				bullets: [
					"Divisional Controller, Traffic Officer, Mechanical Engineer",
					"Administrative Officer, Account Officer, Security Officer",
					"Depot Managers, Stand Incharges, Workshop Incharges",
					"Deputy Engineers and Statistical Officers",
				],
				heading: "Contacts per Division",
				paragraphs: ["Each division lists mobile numbers for key personnel."],
			},
		],
	},
	download: {
		intro:
			"This page provides downloadable application forms and documents for various GSRTC services, including bus hiring, passenger passes, and employment applications. Each document is available as a PDF.",
		sections: [
			{
				bullets: [
					"Material List (new)",
					"Final Hospital Yandi",
					"Hire Bus for Marriage",
					"Casual Contract Application Form",
					"Passenger Pass Application Form",
					"Student Concession Pass Application Form",
				],
				heading: "Downloadable Documents",
			},
		],
	},
	faqs: {
		intro:
			"Answers to frequently asked questions about booking bus tickets, payment options, cancellation policies, and services offered by GSRTC.",
		sections: [
			{
				heading: "How does advance reservation work?",
				paragraphs: [
					"Advance booking lets you select seats, choose boarding points and bus types, and book via online, mobile, or counters up to 60 days in advance. Relief vehicles are provided for breakdowns.",
				],
			},
			{
				heading: "Can I reschedule a booking?",
				paragraphs: [
					"Rescheduling is permitted for advance bookings, with a Rs. 5 reservation charge for online and mobile bookings.",
				],
			},
			{
				heading: "What payment methods are accepted?",
				paragraphs: [
					"Credit/debit cards (RuPay, Mastercard, Visa), UPI, and QR codes. A 1% discount applies on all classes for E and M booking transactions from 11th June 2022 onwards.",
				],
			},
			{
				heading: "What are the child fare rules?",
				paragraphs: [
					"Children under 5 years travel free; children aged 5-12 are charged half fare. Photo ID proof is mandatory for e-ticket travel and tickets are non-transferable.",
				],
			},
			{
				heading: "What if I lose my e-ticket?",
				paragraphs: [
					"Lost e-tickets can be retrieved via the Print/SMS option; counter-purchased tickets require repurchase.",
				],
			},
			{
				heading: "Is there a helpdesk?",
				paragraphs: [
					"Yes, a 24/7 toll-free helpdesk is available at 1800 233 666666. Bus tracking is available via live maps.",
				],
			},
			{
				heading: "How do I book an online commuter pass?",
				paragraphs: [
					'Go to www.gsrtc.in and select the "Bus Pass" option.',
					"The online commuter pass only generates an acknowledgment copy for the ID card and pass. To collect the physical, original copy, visit the selected issue location/counter and show the acknowledgment copy.",
					"Currently only the Commuter Pass system is online; the online Student Pass system is coming soon.",
				],
			},
			{
				heading: "Can an existing commuter pass be renewed online?",
				paragraphs: [
					"Yes, an existing commuter pass can be renewed on the online system.",
				],
			},
			{
				bullets: [
					"Select the pass type from the dropdown (Monthly / Quarterly).",
					"Enter the From Place and To Place; the available Route Code is populated automatically — pick the most suitable route.",
					"Choose the Bus Pass issue location, which is populated based on the selected route.",
					"For an existing pass, enter the ID card or pass number to validate.",
				],
				heading: "What are the steps to book or collect an online pass?",
				paragraphs: [
					"For a new pass, the system automatically generates an Application Number after successful submission.",
				],
			},
			{
				heading: "What is a Bus Pass issue location?",
				paragraphs: [
					"It is the counter you select from a dropdown, at your convenience, where you collect the original physical copy of the ID card/pass.",
					"The online pass only generates an acknowledgment copy; show it at the selected issue location to collect the original physical ID card and pass.",
				],
			},
			{
				heading: "Is a commuter photo required to issue the pass?",
				paragraphs: [
					"Yes. The commuter must upload a self-attested photo, below 10 KB in size.",
				],
			},
			{
				bullets: [
					"Net Banking, Credit Card or Debit Card.",
					'Payment at Counter — choose "Payment at issue location" to generate the acknowledgment copy and pay the final amount at the counter.',
				],
				heading: "What payment options are available to issue a pass?",
				paragraphs: [
					"A new pass requires a fee of ₹20 in addition to the bus pass amount.",
				],
			},
			{
				heading:
					"How long do I have to collect the original pass and ID from the counter?",
				paragraphs: [
					"The original ID/pass must be collected from the counter within three days of the acknowledgment copy being issued.",
				],
			},
		],
	},
	"gsrtc-direct-agents-list": {
		intro:
			"A directory of authorized GSRTC direct agents across Gujarat's divisions, listing their contact numbers, service areas, and validity periods. The list contains 201 entries (including 2 master franchisees) with validity spanning January 2012 through December 2024.",
		sections: [
			{
				heading: "Coverage",
				paragraphs: [
					"Agents operate across districts including Ahmedabad, Amreli, Vadodara, Bharuch, Bhavnagar, Bhuj, Godhra, Himmatnagar, Jamnagar, Junagadh, Mehsana, Nadiad, Palanpur, Rajkot, Surat, and Valsad.",
				],
			},
			{
				bullets: [
					"Serial number",
					"Agent name",
					"Mobile contact number",
					"Division / District",
					"Service address",
					"Effective from date",
					"Effective to date",
				],
				heading: "Table Columns",
			},
			{
				heading: "Notes",
				paragraphs: [
					"Entries cover individual agents and travel agencies authorized to book GSRTC tickets, most with annual validity periods and clickable phone contacts. 201 entries total.",
				],
			},
		],
	},
	"gsrtc-franchisee-agents-list": {
		intro:
			"A directory of authorized GSRTC franchisee agents, listing name, phone number, location, email, and physical address for individuals and agencies authorized to sell GSRTC bus tickets. The list runs to 800+ agents organized in numbered ranges.",
		sections: [
			{
				bullets: [
					"FA List (1-200)",
					"FA List (201-400)",
					"FA List (401-600)",
					"FA List (601-800)",
					"Additional sections continue beyond 800",
				],
				heading: "List Sections",
			},
			{
				bullets: [
					"Sequential number",
					"Agent / agency name",
					"Contact phone number",
					"Operating location",
					"Email address",
					"Physical business address",
				],
				heading: "Entry Fields",
			},
			{
				heading: "Notable Entries",
				paragraphs: [
					"Agents include major ticketing platforms such as Redbus, MakeMyTrip, and Paytm, alongside individual travel agents and small businesses across Gujarat and neighboring states.",
				],
			},
		],
	},
	leadership: {
		intro:
			"This page presents GSRTC's vision and leadership, emphasizing customer service, technological advancement, and value creation for stakeholders.",
		sections: [
			{
				heading: "Leadership Statement",
				paragraphs: [
					"Customer service and growth are the key objectives. Leadership commits to sustaining outreach while addressing emerging challenges and opportunities.",
					"The organization is pursuing upgrades in technology and management practices to generate value for the public, employees, vendors, the state government, and funding providers.",
				],
			},
			{
				heading: "Leadership Profile",
				paragraphs: [
					"Dr. Rajender Kumar, IAS - Vice Chairman & Managing Director, GSRTC, oversees the corporation's operations and strategic direction.",
				],
			},
		],
	},
	performance: {
		intro:
			"Operational results and key performance metrics for the Gujarat State Road Transport Corporation across fiscal years 2019-20 through 2024-25, tracking vehicle operations, revenue, and efficiency.",
		sections: [
			{
				bullets: [
					"Avg schedules operated per day: 6,865 (2019-20) to 6,677 (2024-25), dropping to 5,137 in 2020-21",
					"Avg vehicles on road: 7,038 to 6,894, low of 5,754 in 2020-21",
					"Avg vehicle utilization: 459 to 469 km/day",
					"Total traffic earnings: Rs. 230,209 Lac to Rs. 324,719 Lac, low of 123,350 in 2020-21",
					"Daily passengers: 2,096K to 1,940K, low of 1,104K in 2020-21",
					"Fuel efficiency: around 5.44-5.55 km/liter",
					"Fleet utilization: 80.8% to 82.61%, low of 68.61% in 2020-21",
				],
				heading: "Operational Results (2019-20 to 2024-25)",
				paragraphs: [
					"The data shows recovery and growth after the 2020-21 downturn, with rising revenues and fleet utilization in recent years.",
				],
			},
		],
	},
	"press-release": {
		intro:
			"This page serves as a repository for official press releases and announcements from GSRTC. It provides downloadable documents related to organizational news and updates.",
		sections: [
			{
				bullets: ["National Mobility Summitt 2025 by GSRTC", "Press Release 1"],
				heading: "Press Releases",
			},
		],
	},
	"privacy-policy": {
		intro:
			"This page outlines how GSRTC handles personal information collected through www.gsrtc.in and protects user privacy.",
		sections: [
			{
				heading: "Privacy Protection Standards",
				paragraphs: [
					"www.gsrtc.in respects your privacy and recognizes the need to protect personally identifiable information such as name, address, and phone numbers. Users can generally browse without revealing personal details, though the site tracks domain information for statistical analysis while maintaining individual anonymity.",
				],
			},
			{
				heading: "Information Collection",
				paragraphs: [
					"When personal information is necessary, the organization commits to notifying users beforehand about collection purposes. Users may decline providing requested information and still access the website, though some features may become unavailable.",
				],
			},
			{
				heading: "Security Measures",
				paragraphs: [
					"The organization has implemented technology, security features, and policy guidelines to safeguard personal data from unauthorized access and misuse, and commits to improving security procedures as technology advances.",
				],
			},
			{
				heading: "Policy Updates and Contact",
				paragraphs: [
					"The privacy policy may be updated periodically with new effective dates posted on this page. The organization pledges to address reasonable privacy concerns within five business days of receiving inquiries.",
				],
			},
		],
	},
	"proactive-disclosure-rti": {
		intro:
			"Public access to Right to Information documents from GSRTC, including proactive disclosures from the central office and divisional branches, plus work orders. Each entry links to a downloadable PDF.",
		sections: [
			{
				bullets: [
					"Proactive Disclosure Central Office",
					"Divisions: Ahmedabad, Amreli, Baroda, Bharuch, Bhavnagar, Bhuj, Godhra, Himmatnagar, Jamnagar, Junagadh, Mehsana, Nadiad, Palanpur, Rajkot, Surat, Valsad",
					"Central Workshop",
				],
				heading: "Proactive Disclosure Documents",
				paragraphs: [
					"A table listing RTI materials from GSRTC's central office and 17 divisional branches, plus Central Workshop documentation.",
				],
			},
			{
				bullets: [
					"Workorder - Rajkot Division",
					"Workorder - Bhuj Division",
					"Workorder - Baroda Division",
				],
				heading: "Work Orders",
			},
		],
	},
	recruitment: {
		intro:
			"Central hub for GSRTC recruitment announcements, giving candidates access to job notifications, exam results, merit lists, and related documents for positions such as drivers, conductors, helpers, mechanics, and apprentices.",
		sections: [
			{
				bullets: [
					"OMR-based written exam notifications for Driver and Conductor positions",
					"Helper class temporary waiting list selections for various mechanical positions",
					"Special recruitment drives for persons with disabilities",
				],
				heading: "Recent Announcements",
			},
			{
				bullets: [
					"Exam materials: OMR-based objective written exams, provisional and final answer keys, merit lists, and schedules",
					"Selection and appointment: merit lists, waiting lists, and selection notifications for Driver, Conductor, Mechanic, Helper, and administrative roles",
					"Administrative: caste verification circulars, disability certificates, and SEBC documentation requirements",
					"Apprenticeship: separate notices for apprentice positions at Rajkot Division and Central Workshop",
				],
				heading: "Document Categories",
			},
			{
				heading: "Document Access",
				paragraphs: [
					'The page lists 102+ chronologically numbered entries linking to PDF documents, with most recent entries marked "New".',
				],
			},
		],
	},
	"rtc-act": {
		intro:
			"This page provides access to official regulatory documents governing the Gujarat State Road Transport Corporation, including the foundational RTC Act of 1950 and divisional work order documents.",
		sections: [
			{
				bullets: ["RTC Act 1950 - available as a PDF download"],
				heading: "RTC Act",
			},
			{
				bullets: [
					"Workorder - Rajkot Division (PDF)",
					"Workorder - Bhuj Division (PDF)",
					"Workorder - Baroda Division (PDF)",
				],
				heading: "Work Order",
			},
		],
	},
	sitemap: {
		intro:
			"A directory of links organized by category for the GSRTC website, helping users navigate to services, information sections, and resources.",
		sections: [
			{
				bullets: ["GSRTC Login", "Bus Pass Login"],
				heading: "Application Links",
			},
			{
				bullets: ["Leadership", "Special services", "Achievements", "Tenders"],
				heading: "About Us",
			},
			{
				bullets: [
					"Booking Policies",
					"Divisions",
					"Corporate office details",
					"Performance metrics",
					"Bus inquiry",
				],
				heading: "Passenger Services",
			},
			{
				bullets: [
					"Recruitment",
					"Contact information",
					"Awards",
					"Direct and franchisee agent lists",
					"Blacklisted agencies",
					"Grievance redressal officers for persons with disabilities",
				],
				heading: "Support & General Info",
			},
			{
				bullets: [
					"Privacy Policy",
					"Press releases",
					"Citizen rights documents",
					"Women harassment prevention circular",
					"Service regulations",
				],
				heading: "Policies",
			},
			{
				heading: "Additional Resources",
				paragraphs: [
					"Links to the Gujarat Pavitra Yatradham Vikas Board for pilgrimage bookings, mobile app downloads for Android and iOS, and accessibility features. Toll-free support: 1800 233 666666.",
				],
			},
		],
	},
	"special-services": {
		intro:
			"This page describes GSRTC's specialized bus services beyond standard routes, including festival services, railway connections, pilgrim routes, and a range of premium and economy vehicle options.",
		sections: [
			{
				bullets: [
					"Railway schedule accommodations and connections",
					"Festival-specific services",
					"School and college connectivity",
					"Pilgrim destination routes",
					"Metro link services",
					"Contract-based bus rentals for special occasions",
				],
				heading: "Service Types Offered",
			},
			{
				bullets: [
					"Volvo seater and sleeper variants",
					"AC Seater and AC Sleeper models",
					"Non-AC Sleeper, Gurjarnagari, Express, and Ordinary buses",
					"Intercity Express service",
					"Mini buses for smaller groups",
				],
				heading: "Vehicle Categories",
			},
		],
	},
	tenders: {
		intro:
			"Repository of tender notices and bid documents issued by Gujarat State Road Transport Corporation across departments and procurement categories. The page lists 72 tender entries, each with a downloadable PDF.",
		sections: [
			{
				bullets: [
					"Water pump assemblies",
					"Piston assemblies",
					"Brake liners and brake drums",
					"Bearings, gaskets and rubber parts",
				],
				heading: "Vehicle & Parts Procurement",
				paragraphs: [
					"The majority of tenders cover purchasing of bus components.",
				],
			},
			{
				bullets: [
					"Software development and management",
					"Smart electronic ticketing machines",
					"CCTV surveillance systems",
					"IT technical manpower outsourcing",
				],
				heading: "Technology & Services",
			},
			{
				bullets: [
					"Hiring of buses",
					"Highway hotel finalization",
					"Reservation ticket booking",
					"PU metallic color spray painting",
				],
				heading: "Operations",
			},
			{
				bullets: [
					"Driving test track automation",
					"GeM portal procurement",
					"Advertisement agency appointments",
				],
				heading: "Infrastructure",
			},
		],
	},
};

export const EXTERNAL_LINKS: Record<string, string> = {
	"agent-allotment":
		"https://gsrtc.in/OPRSOnline/preFranchiseeAgentTransaction.do",
	"cancel-ticket":
		"https://www.gsrtc.in/OPRSOnline/preTicketCancellation.do?hiddenAction=TicketCancel&flag=C",
	"e-top-status": "https://gsrtc.in/OPRSPhonepe/preGatewayTransactionStatus.do",
	"gsrtc-agent-login": "https://www.gsrtc.in/OPRSWeb/preUserAuthenticate.do",
	"gujarat-pavitra-yatradham-vikas-board": "https://yatradham.gujarat.gov.in/",
	"india-code": "https://indiacode.nic.in/",
	"new-agent-register":
		"https://gsrtc.in/OPRSOnline/jsp/franchiseeTerms&Conditions.jsp",
	"new-commuter-bus-pass":
		"https://www.gsrtc.in/OPRSPass/preOnlinePassengerNewBusPassSystem.do?hiddenAction=PassengerNewBussPass",
	"print-sms-ticket": "https://www.gsrtc.in/OPRSOnline/prePrintTicket.do",
	"refund-transaction-enquiry":
		"https://gsrtc.in/OPRSPhonepe/preGatewayTransactionStatus.do",
	"reschedule-my-journey":
		"https://gsrtc.in/OPRSOnline/prePonePostPoneTicket.do",
	"service-regulation":
		"https://drive.google.com/file/d/1e0cfVQIlze3gPkZ9slXhMwRG--8a6h52/view",
	"sharvan-tirth-darshan": "https://yatradham.gujarat.gov.in/Booking",
	"unity-booking": "https://www.soutickets.in/#/gsrtc-booking",
	"view-history": "https://www.gsrtc.in/OPRSOnline/preViewBookingHistoryNew.do",
	"waiting-list-ticket-status":
		"https://www.gsrtc.in/OPRSOnline/preWaitingListTicketStatus.do",
	"wallet-account": "https://gsrtc.in/OPRSOnline/preGsrtcWalletAccount.do",
	"wallet-passbook":
		"https://gsrtc.in/OPRSOnline/preGsrtcWalletAccountSummary.do",
};
